version: '3.7'
services:
  keel:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: 1
      REPO_CHART_PATH: helm/petclinic
      REPO_URL: git@iteragit.iteratec.de:bachelors-thesis-aeb/petclinic-deployment.git
      BASIC_AUTH_USER: alwin
      BASIC_AUTH_PASSWORD: "123"
      REPO_BRANCH: dev
    ports:
      - 9300:9300
    volumes:
      - "/home/alwin/.ssh/id_rsa:/root/.ssh/id_rsa"
      - "/home/alwin/.ssh/known_hosts:/root/.ssh/known_hosts"