FROM golang:1.12.0
COPY . /go/src/github.com/alwinius/bow
WORKDIR /go/src/github.com/alwinius/bow
RUN make build

FROM debian:latest
RUN apt-get update && apt-get install -y \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY --from=0 /go/src/github.com/alwinius/bow/cmd/bow/bow /bin/bow
ENTRYPOINT ["/bin/bow"]

EXPOSE 9300