{{- if .Values.persistance.enable }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "bow.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bow.name" . }}
    helm.sh/chart: {{ include "bow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: "{{ .Values.persistance.storageClass }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistance.size }}"
{{- end}}
