{{- if (and .Values.ecr.enabled .Values.ecr.secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bow.name" . }}-aws-ecr
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bow.name" . }}
    chart: {{ template "bow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secretAccessKey:  {{ .Values.ecr.secretAccessKey | b64enc }}
{{- end }}
