{{- if .Values.googleApplicationCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bow.name" . }}-google
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bow.name" . }}
    chart: {{ template "bow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  google-application-credentials.json: {{ .Values.googleApplicationCredentials | quote }}
{{- end }}
