{{- if (and .Values.webhookRelay.enabled .Values.webhookRelay.key .Values.webhookRelay.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bow.name" . }}-webhookrelay
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bow.name" . }}
    chart: {{ template "bow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  key: {{ .Values.webhookRelay.key | b64enc }}
  secret:  {{ .Values.webhookRelay.secret | b64enc }}
{{- end }}
