apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bow.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bow.name" . }}
    chart: {{ template "bow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
