{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bow.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bow.name" . }}
    chart: {{ template "bow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.serviceAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP | quote  }}
  {{- end }}
  ports:
    - port: {{ .Values.service.externalPort }}
  {{- if or (ne .Values.service.type "ClusterIP") (ne .Values.service.clusterIP "None") }}
      targetPort: 9300
  {{- end }}
      protocol: TCP
      name: bow
  selector:
    app: {{ template "bow.name" . }}
  sessionAffinity: None
{{- end }}
